### ISSUE TITLE
GLIBC_2.25 not found

### ISSUE THREAD

**Issue by jammy-git** [brandonlim-hs/wkhtmltopdf-aws-lambda-layer#3]
Installed the eu-west-2 layer for a Larvel Vapor project for use with snappy, but getting this error:
```message: "The exit status code '1' says something went wrong:↵stderr: "/opt/bin/wkhtmltopdf: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /opt/lib/libuuid.so.1)↵"↵stdout: ""↵command: /opt/bin/wkhtmltopdf --lowquality --encoding 'utf-8' --footer-font-size '8' --footer-left 'Please acknowledge receipt of this claim immediately. If this is not confirmed within 30 days it will be treated as conceded.' --footer-right 'Page [page] of [topage]' '/tmp/knp_snappy5f5909c3905599.69498844.html' '/tmp/knp_snappy5f5909c3905ab8.36615393.pdf'."```

I assume it's because Amazon Linux 2 doesn't include all the necessary packages by default, but the main page states these layers are compatible with AL2?

**Comment by brandonlim-hs** [comment]
I have not use Laravel Vapor, so unsure what the actual execution environment is.
According to https://github.com/laravel/vapor-php-build/blob/master/php74/compiler.Dockerfile, it may seem that it uses Amazon Linux. I will try to find out whats causing this issue.

Could you try if this ARN works: `arn:aws:lambda:eu-west-2:347599033421:layer:wkhtmltopdf:1`

That layer ARN was created before wkhtmltopdf changes its build process, so uuid was not required.

**Comment by jammy-git** [comment]
Thanks Brandon!

If I login to our EC2 instance we get the following:

```
Last login: Wed Sep  9 14:42:57 2020 from 

       __|  __|_  )
       _|  (     /   Amazon Linux 2 AMI
      ___|\___|___|

https://aws.amazon.com/amazon-linux-2/
55 package(s) needed for security, out of 137 available
Run "sudo yum update" to apply all updates.
[ec2-user@ip-0-0-0-0 ~]$ cat /etc/os-release
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
```

I'll give the other ARN a try and report back.

**Comment by jammy-git** [comment]
That other ARN has worked! Thank you Brandon.

**Comment by tomchiverton** [comment]
> Could you try if this ARN works: `arn:aws:lambda:eu-west-2:347599033421:layer:wkhtmltopdf:1`
> 
> That layer ARN was created before wkhtmltopdf changes its build process, so uuid was not required.

Was this a change from static to dynamic library loading or something else can anyone remember ?

If looks like "arn:aws:lambda:eu-west-2:347599033421:layer:wkhtmltopdf:1" works OK on Node 20 which is Amazon Linux 2023, where as "arn:aws:lambda:eu-west-1:772088832033:layer:wkhtmltopdf-0_12_6:2" only works on Node 18 or less, which is Amazon Linux 2 ?
